INSERT INTO Docks (code, name) VALUES (03, 'Свидетельство о рождении');
INSERT INTO Docks (code, name) VALUES (07, 'Военный билет');
INSERT INTO Docks (code, name) VALUES (08, 'Временное удостоверение, выданное взамен военного билета');
INSERT INTO Docks (code, name) VALUES (10, 'Паспорт иностранного гражданина');
INSERT INTO Docks (code, name) VALUES (11, 'Свидетельство о рассмотрении ходатайства о признании лица беженцем на территории РФ по существу');
INSERT INTO Docks (code, name) VALUES (12, 'Вид на жительство в Российской Федерации');
INSERT INTO Docks (code, name) VALUES (13, 'Удостоверение беженца');
INSERT INTO Docks (code, name) VALUES (15, 'Разрешение на временное проживание в Российской Федерации');
INSERT INTO Docks (code, name) VALUES (18, 'Свидетельство о предоставлении временного убежища на территории Российской Федерации');
INSERT INTO Docks (code, name) VALUES (21, 'Паспорт гражданина Российской Федерации');
INSERT INTO Docks (code, name) VALUES (23, 'Свидетельство о рождении, выданное уполномоченным органом иностранного государства');
INSERT INTO Docks (code, name) VALUES (24, 'Удостоверение личности военнослужащего Российской Федерации');
INSERT INTO Docks (code, name) VALUES (91, 'Иные документы');

INSERT INTO Countries (code, name) VALUES (616,	'ПОЛЬША');
INSERT INTO Countries (code, name) VALUES (643,	'РОССИЯ');
INSERT INTO Countries (code, name) VALUES (804,	'УКРАИНА');
INSERT INTO Countries (code, name) VALUES (792,	'ТУРЦИЯ');
INSERT INTO Countries (code, name) VALUES (578,	'НОРВЕГИЯ');
INSERT INTO Countries (code, name) VALUES (528,	'НИДЕРЛАНДЫ');
INSERT INTO Countries (code, name) VALUES (484,	'МЕКСИКА');
INSERT INTO Countries (code, name) VALUES (492,	'МОНАКО');
INSERT INTO Countries (code, name) VALUES (496,	'МОНГОЛИЯ');
INSERT INTO Countries (code, name) VALUES (434,	'ЛИВИЯ');
INSERT INTO Countries (code, name) VALUES (438,	'ЛИХТЕНШТЕЙН');
INSERT INTO Countries (code, name) VALUES (440,	'ЛИТВА');
INSERT INTO Countries (code, name) VALUES (442,	'ЛЮКСЕМБУРГ');
INSERT INTO Countries (code, name) VALUES (276,	'ГЕРМАНИЯ');